### ISSUE TITLE
Marks for Mass Assignment Hand-in

### ISSUE THREAD

**Issue by prim0062** [prim0062/ecommerce-pattern-library#2]
@thomasjbradley
Here's the list of assignments/exercises I consider complete in this version.

- Pattern library set-up
- Pattern library hosting
- Typography & colours
- Pattern library customization
- Making patterns
- Buttons!
- So many icons!
- Integrating JavaScript into your pattern library
- Documenting patterns
- Headers & footers
- Sharing code with layouts
- Building pages with patterns
- Preparing product data
- Jekyll generators

**In-progress**
- Images & cards
- Forms & fields
- Navigation & sections
- The leftovers
- Homepage template
- Product details page template

**Comment by thomasjbradley** [comment]
“Typography & colours” is incomplete: there is no styling for `<a>` tags or `<mark>` tags.


![Screen Shot 2020-04-06 at 9 23 59 AM](https://user-images.githubusercontent.com/105192/78563070-617e3300-77e8-11ea-8699-a43cc0a249da.png)
![Screen Shot 2020-04-06 at 9 24 03 AM](https://user-images.githubusercontent.com/105192/78563073-62af6000-77e8-11ea-9d0a-233c95e70bf1.png)

**Comment by thomasjbradley** [comment]
Are the icons supposed to just be circles?

![Screen Shot 2020-04-06 at 9 25 14 AM](https://user-images.githubusercontent.com/105192/78563179-8d011d80-77e8-11ea-873c-bfdba315fb29.png)

**Comment by thomasjbradley** [comment]
Footer is incomplete—it’s just a bunch of placeholder words.
