### ISSUE TITLE
Type and Footer Fix for Marks, Icons Issue

### ISSUE THREAD

**Issue by prim0062** [prim0062/ecommerce-pattern-library#3]
@thomasjbradley
I've styled the Typography <a> and <mark> tags, and adjusted the footer as per the previous issue.

As for the icons, I can't figure this one out.
Why is the <style> tag greyed out? That's whats preventing my icons from displaying properly.
![f0a2eaac8c8ab3a1a6c14dfedde51280](https://user-images.githubusercontent.com/43246445/78946538-fc993600-7a90-11ea-96fd-2de89f373f2d.png)

**Comment by thomasjbradley** [comment]
It’s the way it was exported from Illustrator. Update you SVG settings like this:
https://learn-the-web.algonquindesign.ca/topics/image-formats/#configure-the-svg-settings
