### ISSUE TITLE
Checkout form page template, leftovers for marks

### ISSUE THREAD

**Issue by prim0062** [prim0062/ecommerce-pattern-library#7]
@thomasjbradley

I was getting an error, sorry about that. It was working well on my end so I didn't catch that issue. Fix in the latest revision, as well as finished "leftovers".

**Comment by thomasjbradley** [comment]
What changes did you make for leftovers? New patterns?

**Comment by prim0062** [comment]
I added a favicon. Not sure if that counted as such but it's all I had leftover

**Comment by thomasjbradley** [comment]
👍
